[package]
name = "reduce_example"
version = "0.1.0"
authors = ["Michael X. Grey <grey@openrobotics.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
